let body = document.querySelector("body")
let inp = document.querySelector(".slider")
let numb = document.querySelectorAll(".number")
let reset = document.querySelector(".reset")
let form = document.querySelector(".form")
let id = document.querySelector(".id")
let ids = document.querySelector(".ids")
let gf = document.querySelector(".gf")
let gh = document.querySelector(".gh")
let th = document.querySelector(".th")
let h = document.querySelector(".h")
let f = document.querySelector(".f")
let d = document.querySelector(".d")
let j = document.querySelector(".j")
let k = document.querySelector(".k")
let p = document.querySelector(".p")
let q = document.querySelector(".q")
let w = document.querySelector(".w")
let e = document.querySelector(".e")
let r = document.querySelector(".r")
let y = document.querySelector(".y")
let u = document.querySelector(".u")
let o = document.querySelector(".o")
let v = document.querySelector(".vd")
// if(inp.focus() == inp){
//     // body.style.background = ("red")
//     console.log("hello");
// }

// form.addEventListener("focus", function(){
//     numb.classList.add("cor")
//     body.classList.add("back")
// })
form.addEventListener('focus', (event) => {
    body.classList.toggle("back")
    id.classList.toggle("cor")
    ids.classList.toggle("cor")
    gf.classList.toggle("cor")
    gh.classList.toggle("cor")
    th.classList.toggle("cor")
    h.classList.toggle("cor")
    f.classList.toggle("cor")
    d.classList.toggle("cor")
    j.classList.toggle("cor")
    k.classList.toggle("cor")
    p.classList.toggle("cor")
    q.classList.toggle("cor")
    w.classList.toggle("cor")
    e.classList.toggle("cor")
    r.classList.toggle("cor")
    y.classList.toggle("cor")
    u.classList.toggle("cor")
    o.classList.toggle("cor")
    gf.classList.toggle("bg")
    gh.classList.toggle("bg")
    th.classList.toggle("bg")
    h.classList.toggle("bg")
    f.classList.toggle("bg")
    d.classList.toggle("bg")
    j.classList.toggle("bg")
    k.classList.toggle("bg")
    p.classList.toggle("bg")
    q.classList.toggle("bg")
    w.classList.toggle("bg")
    e.classList.toggle("bg")
    r.classList.toggle("bg")
    y.classList.toggle("bg")
    u.classList.toggle("bg")
    o.classList.toggle("bg")
    v.classList.toggle("g")
    h.classList.toggle("g")
}, true);